apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
  #   nginx.ingress.kubernetes.io/set-real-ip-from: "0.0.0.0/0"
  #   nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  name: ise-mock-ingress
  labels:
    name: ise-mock-ingress
    project: Lame-Wayne
spec:
  ingressClassName: nginx
  rules:
  - host: mock.209.38.185.12.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ise-mock-service
            port: 
              number: 8080
